<a href="https://colab.research.google.com/github/Darshini-A/Data-Mining-and-Business-Intelligence/blob/main/Prac%202%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

data = pd.read_csv("/datapreprocessing.csv")
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [3]:
X = data.iloc[:,:-1].values
Y = data.iloc[:,-1].values
print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') 
imputer = imputer.fit(X[:,1:])
(X[:,1:]) = imputer.transform(X[:,1:])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
print(X)

labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
print(Y)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y)
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[2 27.0 48000.0]
 [0 37.0 67000.0]
 [1 30.0 54000.0]
 [1 40.0 63777.77777777778]
 [2 38.0 61000.0]
 [0 48.0 79000.0]
 [2 38.77777777777778 52000.0]]
[[1 50.0 83000.0]
 [0 44.0 72000.0]
 [0 35.0 58000.0]]
[1 1 0 1 0 1 0]
[0 0 1]


In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[ 1.02899151 -1.56731826 -1.30021354]
 [-1.37198868  0.00499146  0.64766582]
 [-0.17149859 -1.09562535 -0.68509374]
 [-0.17149859  0.47668438  0.31732371]
 [ 1.02899151  0.16222243  0.03254602]
 [-1.37198868  1.73453215  1.87790542]
 [ 1.02899151  0.28451319 -0.89013368]]
[[-0.17149859  2.0489941   2.28798528]
 [-1.37198868  1.10560826  1.16026565]
 [-1.37198868 -0.30947048 -0.27501388]]
